version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pyconcentration"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6442hoiyzb33"
s3_prefix = "pyconcentration"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

